table dimCalendar
	lineageTag: <UUID-dimCalendar>

	measure 'Last Fact Date' =

			CALCULATE (
			    MAX ( <FACT_TABLE>[<FACT_DATE_COLUMN>] ),
			    REMOVEFILTERS ( dimCalendar )
			)
		formatString: General Date
		lineageTag: <UUID-LastFactDate>

	measure 'Is Full Month' =

			VAR MonthEnd =
			    EOMONTH ( MAX ( dimCalendar[Date] ), 0 )
			RETURN
			    MonthEnd <= [Last Fact Date]
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: <UUID-IsFullMonth>

	measure 'Is Full Week' =

			VAR WeekStart =
			    MAX ( dimCalendar[YearWeek (date format)] )
			VAR WeekEnd =
			    WeekStart + 6
			RETURN
			    WeekEnd <= [Last Fact Date]
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: <UUID-IsFullWeek>

	column Date
		formatString: General Date
		lineageTag: <UUID-col-Date>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: <REL-dimCalendar-Date>
			defaultHierarchy: <LDT-Date>.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: <UUID-col-Year>
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column MonthNo
		formatString: 0
		lineageTag: <UUID-col-MonthNo>
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthNo]

		annotation SummarizationSetBy = User

	column Month
		lineageTag: <UUID-col-Month>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Month]

		annotation SummarizationSetBy = Automatic

	column Quarter
		lineageTag: <UUID-col-Quarter>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Quarter]

		annotation SummarizationSetBy = Automatic

	column WeekdayNo
		formatString: 0
		lineageTag: <UUID-col-WeekdayNo>
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WeekdayNo]

		annotation SummarizationSetBy = Automatic

	column Weekday
		lineageTag: <UUID-col-Weekday>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Weekday]

		annotation SummarizationSetBy = Automatic

	column WeekNo
		formatString: 0
		lineageTag: <UUID-col-WeekNo>
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WeekNo]

		annotation SummarizationSetBy = Automatic

	column Week
		lineageTag: <UUID-col-Week>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Week]

		annotation SummarizationSetBy = Automatic

	column 'YearMonth (date format)'
		formatString: yyyy-mm
		lineageTag: <UUID-col-YearMonth>
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearMonth (date format)]

		variation Variation
			isDefault
			relationship: <REL-dimCalendar-YearMonth>
			defaultHierarchy: <LDT-YearMonth>.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'YearWeek (date format)'
		formatString: yyyy-MM-DD
		lineageTag: <UUID-col-YearWeek>
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearWeek (date format)]

		variation Variation
			isDefault
			relationship: <REL-dimCalendar-YearWeek>
			defaultHierarchy: <LDT-YearWeek>.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Day
		lineageTag: <UUID-col-Day>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Day]

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: <UUID-col-DateKey>
		summarizeBy: count
		isNameInferred
		sourceColumn: [DateKey]

		annotation SummarizationSetBy = Automatic

	column MonthDay
		lineageTag: <UUID-col-MonthDay>
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthDay]

		annotation SummarizationSetBy = Automatic

	column 'YearWeek (string format)'
		lineageTag: <UUID-col-YearWeekStr>
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearWeek (string format)]

		annotation SummarizationSetBy = Automatic

	column Half
		lineageTag: <UUID-col-Half>
		summarizeBy: none
		isNameInferred
		sourceColumn: [Half]

		annotation SummarizationSetBy = Automatic

	column YearMonthYYYY
		lineageTag: <UUID-col-YearMonthYYYY>
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearMonthYYYY]

		annotation SummarizationSetBy = Automatic

	column YearMonthYY
		lineageTag: <UUID-col-YearMonthYY>
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearMonthYY]
		sortByColumn: 'YearMonth (date format)'

		annotation SummarizationSetBy = Automatic

	column 'Start of month' =

			STARTOFMONTH (dimCalendar[Date])
		formatString: mmmm yyyy
		lineageTag: <UUID-col-StartOfMonth>
		summarizeBy: none

		variation Variation
			isDefault
			relationship: <REL-dimCalendar-StartOfMonth>
			defaultHierarchy: <LDT-StartOfMonth>.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'New Date' = dimCalendar[Date]
		formatString: General Date
		lineageTag: <UUID-col-NewDate>
		summarizeBy: none

		variation Variation
			isDefault
			relationship: <REL-dimCalendar-NewDate>
			defaultHierarchy: <LDT-NewDate>.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dimCalendar-<UUID-partition> = calculated
		mode: import
		source = ```
				ADDCOLUMNS (
				    CALENDAR(
				        DATE(YEAR(MIN(<FACT_TABLE>[<FACT_DATE_COLUMN>])),MONTH(MIN(<FACT_TABLE>[<FACT_DATE_COLUMN>])),DAY(MIN(<FACT_TABLE>[<FACT_DATE_COLUMN>]))),
				        DATE(YEAR(MAX(<FACT_TABLE>[<FACT_DATE_COLUMN>])),MONTH(MAX(<FACT_TABLE>[<FACT_DATE_COLUMN>])),DAY(MAX(<FACT_TABLE>[<FACT_DATE_COLUMN>])))),

				"DateKey", FORMAT([Date], "YYYYMMDD"),

				"Year", FORMAT([Date], "yyyy"),
				"Half", if(MONTH([Date])<=6,"H1","H2"),

				"MonthNo", MONTH([Date]),

				"Month", FORMAT([Date],"MMM"),

				"Day", FORMAT([Date], "DD"),

				"MonthDay", FORMAT([Date], "MM-DD"),

				"Quarter", FORMAT([Date],"\QQ"),

				"YearMonthYYYY", FORMAT([Date],"YYYY-MM"),
				"YearMonthYY", FORMAT([Date],"YY-MM"),
				"YearMonth (date format)", date(YEAR([date]),month([Date]),1),
				"YearWeek (date format)", [date]-WEEKDAY([Date],2)+1,
				"YearWeek (string format)", YEAR([date]-WEEKDAY([Date],2)+1)&"-"&format(WEEKNUM([date]-WEEKDAY([Date],2)+1,1),"00"),
				"WeekdayNo", WEEKDAY([Date],2), //1-Sun..Sat, 2-Mon..Sat

				"Weekday", FORMAT([Date],"ddd"),

				"WeekNo", WEEKNUM([Date], 2)-1,


				"Week", "W" & WEEKNUM([Date], 2)-1 )
				```

	annotation PBI_Id = <HEX32-dimCalendar>
